setup.cfg
setup.py

minor updates for setup/install

setup: bdist_wheel, python_requires

---

paramiko/kex_curve25519.py
paramiko/transport.py
tests/test_kex.py

minor tweaks to suite my taste :)
cc @fuhry @Conan-Kudo

tweak KexCurve25519 conditional enablement/tests

---

paramiko/channel.py
paramiko/file.py
paramiko/message.py
paramiko/py3compat.py
paramiko/sftp_server.py
tests/test_auth.py
tests/test_file.py
tests/test_pkey.py
tests/test_sftp.py
tests/test_transport.py

not needed since we require python-2.7
port of upstream pull-requests: https://github.com/paramiko/paramiko/pull/1296 https://github.com/paramiko/paramiko/pull/1362

py3compat: clean out unused and unneeded stuff

---

paramiko/sftp_client.py

port of https://github.com/paramiko/paramiko/pull/1374

SFTPClient: more descriptive exception for putfo() confirm failure

---

paramiko/proxy.py

port of https://github.com/paramiko/paramiko/pull/1274 and https://github.com/paramiko/paramiko/pull/1360

proxycommand: more robust subprocess management

---

paramiko/proxy.py

Some people have ProxyCommand lines with somewhat sophisticated shell syntax that really needs to be interpreted by the shell.
OpenSSH runs the actual shell. However, paramiko tries to use shlex to parse the command, and use Popen without the shell. There is some idea of this being better for security (to avoid "shell injection"). But this is already arbitrary command execution, of what the user put in their ssh config - consider that it could be `bash -c 'do evil thing'` or `bash /some/bad/script` or even just `evilcmd`. So, let's go with what OpenSSH does here.
Port of upstream https://github.com/paramiko/paramiko/pull/1207

ProxyCommand: run the command verbatim via the shell

---

paramiko/config.py

a bit more reasonably-easy enhancement to SSHConfig
follow-up to #36

config: better hostname expand, support %i in controlpath

---

paramiko/transport.py
tests/test_transport.py

for un-matched hostkey, instead of generic SSHException
should be backward-compatible because BadHostKeyException is a subclass

transport: connect() should raise BadHostKeyException

---

paramiko/client.py

SSHClient: use load_private_key_file() for explicit key_filename

---

paramiko/sftp_client.py
tests/test_sftp.py

need to read all responses to a batch of readdir() requests
before yielding to caller which might start other requests like open()
(not the hoped-for efficiency, but simple)
should use self._read_response() so that packets
for other file transfers are directed correctly
fixes https://github.com/paramiko/paramiko/issues/1171
and https://github.com/paramiko/paramiko/issues/814

SFTPClient: fix listdir_iter() when reading files during iteration

---

paramiko/pkey.py

where "private" means starting with "_" as is the convention
also move the separate regex parts inline,
instead of having multiple member variables for this

pkey: make OPENSSH_KEY_RE private, related small tweaks

---

paramiko/__init__.py
paramiko/channel.py
paramiko/client.py
tests/test_channelfile.py
tests/test_client.py

channel:  new ChannelFile subclass for stdin, ChannelFile tests

---

doc-requirements.txt
paramiko/_version.py
paramiko/pkey.py

prep for 2.8.0 release

---

paramiko/transport.py

inspired by paramiko/paramiko#1614

auth_interactive_dumb() default handler honors show_input

---

paramiko/_version.py

release version 2.8.2

---

paramiko/auth_handler.py

port of https://github.com/paramiko/paramiko/pull/1724

fix non-ascii usernames in _parse_userauth_request() for python2

---

paramiko/proxy.py

fixes paramiko/paramiko#512
Co-authored-by: Julian Eberius <julian.eberius@radioopt.com>

ProxyCommand recv() cannot use select() on win32

---

.github/workflows/linux.yml

also switch base to ubuntu-20.04 and docs build to python-3.8

tests: update CI matrix with python-3.9

---

paramiko/client.py
paramiko/transport.py

if password is provided but is not an allowed auth method
restores functionality accidentally lost in paramiko-ng-2.7.0
due to https://github.com/ploxiln/paramiko-ng/pull/16/
also move Transport.auth_password() "fallback" functionality
into new Transport.auth_interactive_static() method, for re-use
fixes #87 
alternative to #90

SSHClient: try password for keyboard-interactive

---

sites/docs/installing.rst

rust and dropping support for older python

docs: notes about updated cryptography requirements

---

paramiko/kex_gss.py

port of https://github.com/paramiko/paramiko/pull/1765

gss: fix KexGSSGroup1 client-mode with Python 3

---

.github/workflows/linux.yml
dev-requirements.txt
tests/test_client.py

CI: update test matrix with Python-3.10 etc

---

paramiko/transport.py
tests/test_client.py

inspired by https://github.com/paramiko/paramiko/pull/1678

transport: add timeout for tcp connect (if host/port tuple passed)

---

demos/rforward.py
paramiko/_version.py
paramiko/buffered_pipe.py
paramiko/channel.py
paramiko/common.py
paramiko/hostkeys.py
paramiko/kex_gss.py
paramiko/pkey.py
paramiko/rsakey.py
paramiko/sftp_file.py
paramiko/ssh_gss.py
paramiko/transport.py
paramiko/util.py
tests/loop.py
tests/test_client.py
tests/test_hostkeys.py
tests/test_transport.py

prepare for release 2.7.10

---

paramiko/_version.py
paramiko/hostkeys.py
paramiko/pkey.py
paramiko/rsakey.py
tests/test_client.py
tests/test_hostkeys.py
tests/test_pkey.py

prepare for release 2.8.8

---

.github/workflows/linux.yml
paramiko/ed25519key.py
paramiko/kex_curve25519.py
setup.py
tests/test_pkey.py

port of https://github.com/paramiko/paramiko/pull/1806

ed25519key: remove use of pynacl, use cryptography-2.6+

---

paramiko/ssh_gss.py
setup.py
sites/docs/api/ssh_gss.rst
sites/docs/installing.rst
tests/test_gssapi.py

gssapi: remove support for old gssapi-python package

---

paramiko/agent.py
paramiko/proxy.py
paramiko/sftp.py
paramiko/util.py
tests/test_util.py

New helper util.poll_read() uses poll() if possible, or falls back
to using select() - because select() is limited to a small-ish finite
range of file descriptor numbers, usually up to about 1024, while
poll() works with any file descriptor number. Windows does not
have a usable poll() but pretty much all unixes do.
port of paramiko/paramiko#1189
Co-Authored-By: Olaf Klischat <olaf.klischat@gmail.com>
(re-do of #30)

use poll() instead of select() if possible

---

paramiko/packet.py

due to ETM flow changes
fixes https://github.com/paramiko/paramiko/issues/1794

packet: fix dump_packets debug logging repeating bytes

---

paramiko/packet.py

due to ETM flow changes
fixes paramiko/paramiko#1794

packet: fix dump_packets debug logging repeating bytes (backport for 2.8)

---

doc-requirements.txt

add "six" to requirements for "releases" (??)

CI: fix documentation site build in CI

---

paramiko/agent.py
paramiko/ecdsakey.py
paramiko/ed25519key.py
paramiko/kex_group14.py
paramiko/kex_group16.py
paramiko/kex_gss.py
paramiko/proxy.py
paramiko/server.py
paramiko/sftp_attr.py
paramiko/sftp_client.py
paramiko/sftp_server.py
paramiko/transport.py
sites/docs/old_changelog.rst
tests/test_sftp.py

ported from:
https://github.com/paramiko/paramiko/pull/1803
https://github.com/paramiko/paramiko/pull/1972

Tiny cleanups 2022-06

---

.github/workflows/linux.yml
dev-requirements.txt
setup.py

* newer cryptography versions
* update github actions versions

CI: update test matrix, drop python-3.4, add python-3.11

---

.github/workflows/linux.yml
dev-requirements.txt

ci: update base OS, python versions, cryptography versions

---

paramiko/pkey.py
paramiko/transport.py

avoid Cryptography package warnings about this old kinda-weak cipher

remove cipher 3des-cbc, for key decrypt import from "decrepit"
