ploxiln/paramiko-ng

paramiko/auth_handler.py
paramiko/transport.py

Even though the AuthHandler fields the MSG_USERAUTH_BANNER message, any
followup authentication will discard the Transport’s AuthHandler, along
with the saved banner.
fixes paramiko/paramiko#432
copied from upstream PR https://github.com/paramiko/paramiko/pull/438

Save SSH banner to Transport instead of AuthHandler

---

paramiko/transport.py

on rare occasion, assuming the tuple had two parts caused an exception
but no need to format the 2-tuple into a message anyway,
the class can do that itself
still fallback to repr() because I think I've seen empty str() result,
on very rare occasion

always log socket.error with str() or repr()

---

paramiko/ed25519key.py

fixes paramiko/paramiko#1306
support up to 15 bytes padding ... should only be up to 7,
but test key has 8 bytes of padding, not sure if realistic
port from https://github.com/paramiko/paramiko/pull/1400

fix ed25519 ssh key unpad() when padding not present (not needed)

---

paramiko/hostkeys.py

import MutableMapping from collections.abc instead of collections

---

.travis.yml
paramiko/ecdsakey.py
paramiko/kex_ecdh_nist.py
tests/test_client.py
tests/test_gssapi.py
tests/test_kex.py
tests/test_kex_gss.py
tests/test_ssh_gss.py
tests/test_util.py

assertEquals() is long deprecated in favor of assertEqual()
cryptography-2.5+ wants different key bytes functions to be used

avoid deprecation warnings

---

paramiko/transport.py
tests/test_transport.py

These are being removed from OpenSSH as well:
https://github.com/openssh/openssh-portable/commit/714e367226ded4dc3897078be48b961637350b05
port of https://github.com/paramiko/paramiko/pull/688

Removed support for hmac-md5 and truncated hmac-sha1

---

paramiko/kex_curve25519.py
paramiko/transport.py
tests/test_kex.py

This commit introduces support for the `curve25519-sha256@libssh.org` key exchange method, which is the currently (August 2018) recommended method for all modern SSH servers and clients.
Client mode, server mode and unit tests are included and have been tested with the OpenSSH client and server.

kex: support curve25519-sha256@libssh.org

---

.travis.yml
paramiko/ssh_gss.py
setup.py
sites/docs/api/ssh_gss.rst
tests/test_gssapi.py
tests/test_kex_gss.py
tests/test_ssh_gss.py
tests/util.py

Previously paramiko supported the older "gssapi-python" package, optionally - but if the newer "gssapi" package happened to be present, the initial "import gssapi" would succeed, and then trying to reference bits of it would fail, and importing paramiko would completely fail as a result.
port of https://github.com/paramiko/paramiko/issues/584
via https://github.com/paramiko/paramiko/pull/861
via https://github.com/paramiko/paramiko/pull/1311

support newer "gssapi" package

---

paramiko/message.py
tests/test_message.py

I suspect that "adaptive int" is not really a thing in SSH. I'll let this sit a while and try to confirm before merge.
At some point get_int() was made adaptive, which was a bug ... when it was fixed the incorrect functionality was moved to a new function.
Also, Message.add() was warns about long not being encoded in a deterministic way, saying "don't use this", and it's just because of these "adaptive" ints.
see https://github.com/paramiko/paramiko/pull/482 commit 70924234bb70d15005e4ce18305fc610482acf1b

message: remove add_adaptive_int() and get_adaptive_int()

---

paramiko/client.py

Previously, if not look_for_keys, would look for keys,
and then discard the results. Instead, skip the search.
inspired by https://github.com/paramiko/paramiko/pull/1243

SSHClient: better look_for_keys=False behavior

---

paramiko/client.py
paramiko/transport.py

Some systems are configured to close the connection after one
authentication attempt.  If this is the case and we are provided with
To fix that, we need to detect the allowed authentication methods and
only try public key or password if those are allowed.
Also enables the "no auth" case, used by some appliances, to work.
port of https://github.com/paramiko/paramiko/pull/1106

sshclient: detect allowed authentication types

---

paramiko/client.py

previously it was completely ignored
port of https://github.com/paramiko/paramiko/pull/1250

SSHClient: invoke_shell() should use environment argument

---

paramiko/file.py

Fixes paramiko/paramiko#1196
self._buffer is copied by ref to the line variable, but since bytes
type is immutable, adding data to the line further on, actually makes
it to diverge from self._buffer. Therefore if timeout occurs, the data
that was read during the readline() execution so far, gets lost.
The idea is to save temporary buffer back to the original if we hit timeout.
port of https://github.com/paramiko/paramiko/pull/1197

BufferedFile: save temp buffer on readline() timeout

---

tests/test_buffered_pipe.py
tests/test_client.py
tests/test_file.py
tests/test_gssapi.py
tests/test_hostkeys.py
tests/test_kex.py
tests/test_kex_gss.py
tests/test_message.py
tests/test_packetizer.py
tests/test_pkey.py
tests/test_sftp.py
tests/test_sftp_big.py
tests/test_ssh_gss.py
tests/test_transport.py

many old tests had names of form `test_[9-0A-Z]+_.*`

tests: remove numbering from test function names

---

paramiko/kex_curve25519.py
paramiko/kex_group16.py

an alias of is_supported(), in order to be compatible with
upstream's (more recently added) variant

KexCurve25519: add is_available() method

---

paramiko/buffered_pipe.py
paramiko/channel.py
paramiko/pipe.py
tests/test_transport.py

In the context of fileno(), a Channel's .in_buffer and .in_stderr_buffer
operate on a pair of of OrPipes obtained from make_or_pipe(). These two
cooperate and share the same underlying PosixPipe resp. WindowsPipe.
Due to the lack of any synchronization in the OrPipe's .set() method, it
is possible (and has actually been observed) to have both OrPipes'
._set = True while the underlying pipe remains unset.
Fix that by adding proper locking to the OrPipe implementation.
port of https://github.com/paramiko/paramiko/pull/1235
EDIT: added
port of https://github.com/paramiko/paramiko/pull/1158
see also https://github.com/paramiko/paramiko/issues/1157

channel: fileno pipe race fixes

---

paramiko/transport.py

These KEX algorithms seem to work with openssh server, but there have
been reported compatibility issues with some other implementations:
https://github.com/paramiko/paramiko/issues/1455

transport: do not prefer kex group16_sha512 and group14_sha256

---

paramiko/transport.py

According to paramiko/paramiko#1459, Solaris 8 ssh server can offer a language list which includes 0xff bytes.
The client_lang_list and server_lang_list do not matter, they are only debug-logged, so just debug-log the bytes repr (instead of trying to decode a string and split into a list).

transport: do not decode language lists

---

paramiko/ssh_exception.py
tests/test_ssh_exception.py

Setting "self.args" is equivalent to calling the parent class
`__init__()` method with those args, and also overrides the only
thing that parent class `__init__()` method did. It is confused.
What is actually desired is to override the `__str__()` method with
a custom formatted exception message. The default for Exception
with zero args is blank, with one arg is the str of that arg,
with multiple args is just the repr of the args tuple.
(That never includes the class name. So, we want custom str.)
inspired by https://github.com/paramiko/paramiko/issues/1440

clean up SSHException subclass args and string methods

---

paramiko/auth_handler.py
paramiko/packet.py
paramiko/sftp_server.py
paramiko/transport.py
tests/test_auth.py

issubclass() was being used in odd ways, probably due to
limitations in very old versions of python (no longer supported)
inspired by https://github.com/paramiko/paramiko/pull/1550

replace issubclass() with isinstance() everywhere

---

paramiko/kex_group1.py
paramiko/transport.py

was always using sha1 instead of the appropriate hash function
fixes https://github.com/paramiko/paramiko/issues/1462
raised by https://github.com/paramiko/paramiko/issues/1455

kex: fix server-side of kex-group-14-sha256 and kex-group16-sha512

---

demos/forward.py
demos/rforward.py

to avoid losing bytes when send buffer/window fills up
Fixes paramiko/paramiko#511
This fix is not ideal. Since sendall() blocks until all data is sent,
there may be a risk of a deadlock if there is data congestion in both
directions simultaneously. However, the likelihood is significantly
lower than the likelihood of hitting the current bug where bytes are
lost.
port of https://github.com/paramiko/paramiko/pull/1244

demos: Use sendall() instead of send() for port forwarding

---

paramiko/file.py

Since result is managed through repeat string
concatenation, runtime is quadratic in the number of successful
calls to read().
In Python 2 this had reasonable runtime because Python/ceval.c contained
a special case for appending to a string that could be safely mutated,
as the only reference to it existed on the stack.
("Python/ceval.c::string_concatenate()"), however during the great
Python 3.x transition this special case was rewritten to only support
Unicode, causing a huge amount of heap churn and memory copies on 3.x.
fixes paramiko/paramiko#1141
port of upstream https://github.com/paramiko/paramiko/pull/1479

BufferedFile: avoid quadratic buffer append with Python 3.x

---

demos/demo.py
demos/demo_server.py
paramiko/__init__.py
paramiko/dsskey.py
paramiko/ecdsakey.py
paramiko/ed25519key.py
paramiko/pkey.py
paramiko/rsakey.py
sites/docs/api/keys.rst
tests/conftest.py
tests/test_auth.py
tests/test_kex_gss.py
tests/test_pkey.py
tests/test_ssh_gss.py

Two new functions were created:
* load_private_key(key_str, password=None)
* load_private_key_file(filename, password=None)
Previously there was no way to auto-load any key type. Many downstream
users re-implemented this logic themselves, which is pointless
duplication and could easily become outdated when new key types are
added.
This functionality required a significant refactoring of key creation
code paths, but none of the public interfaces have changed.

Add functions to auto-detect and load any private key type

---

paramiko/__init__.py
tests/test_util.py

enable flake8 for this file
remove unused "import sys"
add all "top-level symbols" to `__all__`
remove `BaseSFTP` from this top-level-symbols list
(surely no direct users ...)

cleanup __init__.py

---

.travis.yml
paramiko/pkey.py
tests/test_pkey.py

accidentally broken when adding new openssh format private key support
fixes https://github.com/paramiko/paramiko/issues/1580

pkey: fix loading original format with leading whitespace

---

.travis.yml
paramiko/pkey.py
tests/test_pkey.py

accidentally broken when adding new openssh format private key support in paramiko-ng-2.6 via #13

pkey: fix loading original format with whitespace/comments (2.7 branch)

---

tests/test_pkey.py

regression introduced back in #13 and unintentionally fixed in #57

test pkey loading old format with leading whitespace or comments

---

paramiko/transport.py

Adding exception handling for packetizer race condition when the server ends
the session before the client. This can occur when utilizing fabric2 2.5.0 and
sends a high volume of commands through a Connection() object, then trying to
close the object.
The EOFError is being raised when trying to write out the final bytes to close
the socket, but the socket is already closed. This does not prevent the rest of
the transport object shutdown properly, so a warning log is written out instead
of raising the exception higher.
port of https://github.com/paramiko/paramiko/pull/1585

transport: gracefully handle EOFError when closing packetizer

---

paramiko/file.py

more efficient when uploading large buffers
port of https://github.com/paramiko/paramiko/pull/1337

BufferedFile: use memoryview in _write_all()

---

dev-requirements.txt
tests/test_channelfile.py
tests/test_transport.py

Prefer and use built-in unittest.mock in Python 3.3+ instead
of unnecessarily requiring the external mock package.  This helps
distributions that are phasing out Python 2 to remove redundant
packages.
port of https://github.com/paramiko/paramiko/pull/1666

prefer stdlib unittest.mock over external package

---

demos/demo.py
paramiko/auth_handler.py
paramiko/client.py
paramiko/kex_gex.py
paramiko/kex_gss.py
paramiko/server.py
paramiko/sftp.py
paramiko/sftp_client.py
paramiko/sftp_file.py
paramiko/sftp_server.py
paramiko/transport.py
paramiko/util.py
tests/test_kex.py
tests/test_sftp.py
tests/test_util.py

Transport._log() does not take msg list, it takes format string
SFTPClient/SFTPServer _log() method does not take msg list
SFTPBase gets new _loglist() method for the rare list case
Transport and SFTP* use proper logging format strings
and separate arguments
SSHClient and AuthHandler always log with single msg string,
so pass to Transport._log() as "%s", msg
get rid of util.tb_strings(), instead _log() with exc_info=True
so that lines of traceback are not separate log messages
(inspired by https://github.com/paramiko/paramiko/pull/406)

logging reform: Transport,SFTP* _log() refactor

---

.github/workflows/linux.yml
paramiko/rsakey.py

This currently works, because OpenSSL simply re-computes iqmp when
it doesn't match the p & q values. However a future pyca/cryptography
patch enforces this.
port of https://github.com/paramiko/paramiko/pull/1723

RSA key loading: p and q were swapped

---

paramiko/channel.py

fixes paramiko/paramiko#1705
fixes paramiko/paramiko#1584
TODO: confirm with the reproducer script helpfully included in https://github.com/paramiko/paramiko/issues/1705

channel: check if already closed in _send_eof() 

---

demos/rforward.py
paramiko/buffered_pipe.py
paramiko/channel.py
paramiko/sftp_file.py
paramiko/transport.py
paramiko/util.py
tests/loop.py
tests/test_transport.py

the new method names were added way back in Python-2.6
port of https://github.com/paramiko/paramiko/pull/1870

update Thread method calls deprecated in Python-3.10

---

paramiko/common.py

This reverts commit 7c1d29c97c2e4861953706c8d0197ad399178b86
Using exception handling for control flow in common.asbytes()
resulted in degraded performance for sftp transfer of large files
reported in paramiko/paramiko#1660
port of https://github.com/paramiko/paramiko/pull/1884

Revert "Leverage b() in asbytes() to avoid duplication."

---

paramiko/channel.py
paramiko/transport.py

While the channel tracks its state for generating messages under
its own lock, it needs to release that lock before calling the
transport method to send a message, which uses the transport's lock.
Messages could be generated under the correct conditions and in the
correct order, but then sent in a different order, if two different
threads are calling channel methods.
This was made much more likely by the recent addition of
ChannelStdinFile (in paramiko-ng 2.8.0) which calls shutdown_write()
automatically when closed. So, for now, protect only EOF to fix the
immediate regression, and reduce code churn. There is already a mess
of state checking of dubious robustness, e.g. the open_only()
decorator ...
This problem was well described in paramiko/paramiko#1115 and this
solution is heavily …

channel: fix race between sending channel EOF and CLOSE messages

---

paramiko/__init__.py
paramiko/transport.py

also, probably better not to include `__version__` in `__all__`

add paramiko.__pkgname__ to help distinguish from upstream paramiko

---

paramiko/pkey.py
tests/test_pkey.py

... because `hash()` is too weak and not intended for this.
Also simplify `__cmp__()` (which did work fine).
This fixes a security flaw. If you are using Paramiko with Python 2, or a Python 3 which is running with PYTHONHASHSEED=0, it is possible for an attacker to craft a new keypair from an exfiltrated public key, which Paramiko would consider equal to the original key.
This could enable attacks such as:
* Paramiko server processes would incorrectly authenticate the attacker (using their generated private key) as if they were the victim.
* Paramiko client processes would incorrectly validate a connected server (when host key verification is enabled) while subjected to a man-in-the-middle attack. This impacts more users than the server-side version, but also carries higher requirements …

pkey: __eq__() should not use hash()

---

paramiko/hostkeys.py
tests/test_hostkeys.py

If the specified key type is found out, the exception KeyError should
not happen.
port of https://github.com/paramiko/paramiko/pull/1024

hostkeys: fix raising KeyError in SubDict.__delitem__()

---

paramiko/ecdsakey.py
paramiko/rsakey.py

... when using Cryptography to load private key material.
Prior to this change, these exceptions bubble up as-is instead of becoming
SSHException instances like most other key-loading errors.
port of https://github.com/paramiko/paramiko/pull/1266 / https://github.com/paramiko/paramiko/commit/6b1513e79a3244ccd5879fdd3399ea97f87f16f9

rsakey,ecdsakey: catch TypeError and UnsupportedAlgorithm

---

tests/test_client.py

GC is unpredictable, but this does often work ... just give more
time and attempts to hopefully get close enough to 100%

tests: another attempt to make SSHClient test_cleanup more reliable

---

paramiko/rsakey.py

Patch author noticed that paramiko ssh server rejects userauth request when
PuTTY connects with an RSA key, about 1% of the time.
OpenSSH server pads leading zeros to a signature before verifying it.
Putty even has an FAQ about this particular bug, explaining that:
> The SSH-2 specification says that an unpadded signature MUST be accepted
https://github.com/openssh/openssh-portable/blob/V_8_8_P1/ssh-rsa.c#L296-L312
https://documentation.help/PuTTY/config-ssh-bug-sig.html
port of https://github.com/paramiko/paramiko/pull/1933

rsakey: pad received signature with leading zeros

---

paramiko/pkey.py
tests/test_pkey.py

the SSHClient attempts to load multiple key files, so it
reduces confusion to see what key file an exception is about
inspired by https://github.com/paramiko/paramiko/pull/1647

pkey: add filename to exceptions raised while reading keys

---

paramiko/channel.py

Implemented as per section 6.9 of RFC 4254 ("The Secure Shell (SSH)
Connection Protocol"). Support for this request was added in OpenSSH
7.9. Support in other implementations may vary.
port of https://github.com/paramiko/paramiko/pull/1535

Add send_signal method to Channel

---

demos/demo.py
demos/demo_keygen.py
demos/demo_server.py
paramiko/client.py
paramiko/pkey.py
tests/test_pkey.py

New method `fingerprint_sha256_b64()` gives the fingerprint format just like openssh has for a while (and avoids `md5()` which is problematic for security policy compliance stuff).
----------
inspired by https://github.com/paramiko/paramiko/pull/1103
addresses https://github.com/paramiko/paramiko/issues/1758

pkey: new method get_fingerprint_sha256_b64()

---

paramiko/agent.py
paramiko/dsskey.py
paramiko/ecdsakey.py
paramiko/ed25519key.py
paramiko/pkey.py
paramiko/rsakey.py
tests/test_pkey.py

Just use `asbytes()` in `__hash__()` for simplicity.
For python3, `__str__()` would raise exceptions for most
key types, and was uselessly mangled for RSAKey. Make it
return a string with type and fingerprint.
(Keep old behavior for python2: public key bytes.)
fixes https://github.com/paramiko/paramiko/issues/853

pkey: shared implementation of __hash__() and __str__()

---

paramiko/agent.py
paramiko/dsskey.py
paramiko/ecdsakey.py
paramiko/pkey.py
paramiko/rsakey.py
tests/test_pkey.py

For python3, `__str__()` would raise exceptions for most
key types, and was uselessly mangled for RSAKey. Make it
return a string with type and fingerprint.
(Keep old behavior for python2: public key bytes.)
Also give AgentKey a `__hash__()` implementation.
fixes https://github.com/paramiko/paramiko/issues/853
partial backport of 30a09ce6dd9b from ploxiln/paramiko-ng#114
(but need to inline sha256-base64 fingerprint style)

pkey: fix __str__() for python3 (backport for 2.7)

---

paramiko/agent.py
paramiko/dsskey.py
paramiko/ecdsakey.py
paramiko/pkey.py
paramiko/rsakey.py
tests/test_pkey.py

For python3, `__str__()` would raise exceptions for most
key types, and was uselessly mangled for RSAKey. Make it
return a string with type and fingerprint.
(Keep old behavior for python2: public key bytes.)
Also give AgentKey a `__hash__()` implementation.
fixes https://github.com/paramiko/paramiko/issues/853
partial backport of 30a09ce6dd9b from ploxiln/paramiko-ng#114
(but need to inline sha256-base64 fingerprint style)

pkey: fix __str__() for python3 (backport for 2.8)

---

paramiko/client.py
paramiko/transport.py
sites/docs/conf.py

Also update connect() documentation - note when auth_timeout
was added, and re-order params in the docs a bit
(the order already differed from the function signature,
which keeps the original order for now).

SSHClient: add handshake_timeout kwarg to connect()

---

paramiko/pkey.py
tests/test_pkey.py

A bug introduced by 11025ca20b51 (added in v2.7.10) and fixed for python3 in f94529828753 (not yet released on the 2.7 branch).
This bug is hit by SSHClient.connect() if the key in known_hosts is a type that the remote does not offer ... and possibly other cases. (It would raise the wrong exception.)
Reported upstream (in slightly different situation) in https://github.com/paramiko/paramiko/pull/1964
backport of #124

pkey: fix comparison with None for python2 (2.7 branch)

---

paramiko/pkey.py
tests/test_pkey.py

A bug introduced by #106 (79da092beb51) and fixed for python3 in #114 (30a09ce6dd9b).
This bug is hit by `SSHClient.connect()` if the key in known_hosts is a type that the remote does not offer ... and possibly other cases. (It would raise the wrong exception.)
Reported upstream (in _slightly_ different situation) in https://github.com/paramiko/paramiko/pull/1964

pkey: fix comparison with None for python2

---

paramiko/pkey.py
tests/test_pkey.py

A bug introduced by 40daf204b339 (added in v2.8.8) and fixed for python3 in ca3839ebc86c (not yet released on the 2.8 branch).
This bug is hit by SSHClient.connect() if the key in known_hosts is a type that the remote does not offer ... and possibly other cases. (It would raise the wrong exception.)
Reported upstream (in slightly different situation) in https://github.com/paramiko/paramiko/pull/1964
backport of #124

pkey: fix comparison with None for python2 (2.8 branch)

---

README.rst
paramiko/ber.py
paramiko/channel.py
paramiko/client.py
paramiko/config.py
paramiko/dsskey.py
paramiko/ecdsakey.py
paramiko/message.py
paramiko/pkey.py
paramiko/rsakey.py
paramiko/sftp_server.py
paramiko/ssh_gss.py
paramiko/transport.py
setup.py
sites/docs/conf.py
sites/docs/installing.rst

~in progress~ done ... ~need to move some `__init__()` docs to the class itself, and mention pkey comparison there too~ nope, backed this out, was too much churn, plenty of easier bits to clean up

docs: cleanup method pydocs a bit

---

paramiko/transport.py
tests/test_transport.py

ETM means "encrypt then mac". OpenSSH prefers ETM, it's a good idea.

transport: prefer ETM mac by default

---

paramiko/transport.py
tests/test_transport.py

Backport https://github.com/paramiko/paramiko/pull/2039
Fixes #135.

Remove blowfish from transport ciphers

---

paramiko/client.py
paramiko/transport.py

Re-uses the transport SecurityOptions directly ... but needs to
create a "shadow transport" just for the options, because SSHClient
always creates the Transport (and obtains the socket needed to
create the Transport) in SSHClient.connect() - it can copy from
the "dummy transport" SecurityOptions between creating and using
the real Transport.

SSHClient: add get_security_options()

---

paramiko/util.py

Avoid leaking memory by only ever adding to the thread IDs dict
fixes paramiko/paramiko#2002
port of https://github.com/paramiko/paramiko/pull/2003

util: store thread assigned id in thread-local storage

---

paramiko/agent.py
paramiko/win_openssh.py

In addition to Putty's "Pageant" agent, there is now a native openssh
port for windows. If the Putty pageant is not present, try to use the
native port's agent instead.
port of https://github.com/paramiko/paramiko/pull/1868

agent: support OpenSSH agent on Windows

---

paramiko/sftp_client.py

Co-Authored-By: Christophe Vu-Brugier <cvubrugier@fastmail.fm>
port of paramiko/paramiko#2084 (partial/minimal)

sftp client: fix getfo() docstring mixup of remotepath and fl

---

tests/test_client.py

this still often flakes for 1 out of 20 CI matrix cases randomly

tests: one last attempt to make client test_cleanup consistent

---

paramiko/win_openssh.py

* use os.listdir() instead of os.path.exists(), because on windows the
latter uses CreateFileW() and the pipe cannot be reopened unless the
server calls DisconnectNamedPipe()
* retry when open() raises Errno 22 which means that the server has not
called DisconnectNamedPipe() yet
* use os.{open,read,write,close}() because self._pipe.read() raises
IOError: [Errno 0] on Python 2
follow-up to ploxiln/paramiko-ng#134
port of paramiko/paramiko#2010

agent: win_openssh: use appropriate syscalls

---

paramiko/util.py

Avoid leaking memory by only ever adding to the thread IDs dict.

util: store thread assigned id in thread-local storage (backport for 2.8)

---

demos/interactive.py

TypeError: write() argument must be str, not byte
port of https://github.com/paramiko/paramiko/pull/2098

demos: fix TypeError in interactive shell on Windows

---

paramiko/client.py

If non-None value is passed in, it's used when opening a new ssh channel. If value is None, value of 'timeout' kwarg is used.

Add open_timeout kwarg to exec_command()

---

paramiko/transport.py

appending exception string to "banner" with no separator is weird
---------------
pointed out in https://github.com/ploxiln/fab-classic/issues/76

transport: improve protocol banner exception string

---

paramiko/packet.py
paramiko/sftp.py

Type-switch based code is used to convert a value to bytes. However, in all cases (except for one, fixed in this PR), the caller is specifying a Message instance. We can make this code much simpler by directly calling the correct method on Message.
(This might not have as large an effect on this fork as on upstream, because this fork doesn't use try/except for type check in asbytes() helper.)
port of https://github.com/paramiko/paramiko/pull/2165

improve performance by calling Message.asbytes() directly
